/* ══════════════════════════════════════════════════════════
   PŘEDMĚTY — Svět Aekildae
   Samostatný datový soubor pro import do wiki
   ══════════════════════════════════════════════════════════ */

const ITEMS_DATA = [
{
  id: "einstein-rosenuv-mesec",
  name: "Einstein-Rosenův měšec",
  categories: ["Batohy", "Magické předměty"],
  subcategory: "Měšce",
  rarity: "Vzácný",
  icon: "👝",
  excerpt: "Měšec otevírající cestu do rozdílného časoprostoru. Pojme mnohem víc předmětů, než odpovídá jeho rozměrům.",
  type: "Zázračný předmět (úložný)",
  damage: "",
  ac: "",
  cost: "",
  weight: "0.2 kg",
  material: "Aethericky napuštěná useň, zlatý filigránový vzor",
  properties: "Kapacita: 1000 mincí nebo 250 drahých kamenů. Rozměry: 5 × 10 palců (12,7 × 25,4 cm).",
  special: "Otevírá cestu do rozdílného časoprostoru — vnitřní prostor je mnohonásobně větší než vnější rozměry. Fialová interdimenzionální výplň uvnitř.",
  description: "Einstein-Rosenův měšec je zázračný úložný předmět využívající principu interdimenzionálního prostoru. Zvenku vypadá jako elegantní kožený měšec zdobený zlatým filigránovým vzorem na hnědé usni. Uvnitř se otevírá fialově zářící prostor pojmoucí mnohem více předmětů, než by odpovídalo jeho fyzickým rozměrům — až 1000 mincí nebo 250 drahých kamenů.",
  crafting: "Vyroben z v éteru aethericky napuštěné usně se zlatým filigrán. Mk. II verze obsahuje vnitřní kapsu pro runový stabilizátor. Kruhové dno (průměr 12,7 cm). Interdimenzionální fialová výplň se vkládá jako vložka (průměr 20 cm). Celkový rozvinutý rozměr: 40,6 × 25,4 cm.",
  history: "",
  trivia: "Technický plánek nese označení Mk. II (nesestavený). Název odkazuje na Einstein-Rosenův most — teoretický průchod časoprostorem.",
  image: "img/casoprostorovy_mesec.png",
  blueprint: "img/einstein-rosenuv-mesec-planek.png",
  attunement: "Ne",
  relatedIds: []
},
{
  id: "maskovaci-plast-amgilched",
  name: "Maskovací Plášť Amgilched",
  categories: ["Pláště", "Magické předměty"],
  subcategory: "Magické pláště",
  rarity: "Velmi vzácný",
  icon: "🧥",
  excerpt: "Plášť kapitána Gefrraye Bricota z Halle. Poskytuje mimořádné maskovací schopnosti a ochranu proti nižší magii.",
  type: "Zázračný předmět (plášť)",
  damage: "",
  ac: "",
  cost: "",
  weight: "2.5 kg",
  material: "Dračí šupiny, zelené listové peří, zlatá spona",
  properties: "+3 na Nenápadnost (s výhodou k hodům). První útok ze zálohy je vždy Kritický.",
  special: "+3 na Nenápadnost — ke všem hodům na Nenápadnost máš výhodu. Tvůj první útok ze zálohy je vždy Kritický zásah. Poskytuje odolnost proti veškerým magickým zásahům kouzly do 4. stupně.",
  description: "Maskovací Plášť Amgilched je mistrovský kus krejčovského a magického umění. Plášť má kapuci lemovanou zlatým okrajem a je sepnut ozdobnou zlatou sponou ve tvaru propletených listů. Vnější strana je pokryta vrstvou zelených šupinovitých lístků připomínajících dračí šupiny, které postupně přecházejí v hustou texturu podobnou listovému peří. Vnitřní strana je z černé látky. Spodní okraj pláště je nepravidelně roztřepený jako rozervané listí.",
  crafting: "",
  history: "Plášť patřil kapitánovi Gefrraye Bricotovi z Halle. Okolnosti jeho výroby a původu jsou zahaleny tajemstvím.",
  trivia: "Plášť je zobrazen ze čtyř pohledů na technickém plánku — přední, zadní, boční a detail kapuce. Detail spony ukazuje propletený listový motiv. Materiál na dotek připomíná skutečné listy, ale je tvrdý jako dračí šupiny.",
  image: "img/Amgilched.png",
  blueprint: "img/Amgilched_planek.png",
  attunement: "Ano",
  relatedIds: []
},
{
  id: "amulet-pohyblivosti",
  name: "Amulet pohyblivosti",
  categories: ["Šperky", "Magické předměty"],
  subcategory: "Náhrdelníky",
  rarity: "Neobvyklý",
  icon: "💎",
  excerpt: "Jednoduchý malachitový amulet zlepšující obratnost vlastníka. Stačí jej nosit na krku.",
  type: "Zázračný předmět (amulet)",
  damage: "",
  ac: "",
  cost: "",
  weight: "0.1 kg",
  material: "Malachit, stříbrný řetízek",
  properties: "Pasivní efekt: Obratnost +1",
  special: "Zvyšuje hodnotu Obratnosti nositele o 1 bod, pokud je nošen na krku. Efekt je pasivní a nevyžaduje aktivaci.",
  description: "Amulet pohyblivosti je nenápadný, ale účinný magický předmět. Skládá se z hrubě opracovaného malachitového hrotu ve tvaru šípové hlavice, zavěšeného na jednoduchém stříbrném splétaném řetízku. Malachit má charakteristickou sytě zelenou barvu s průsvitnými krystalickými plochami, které na světle jemně svítí. Kámen je uchycen stříbrnou objímkou a působí dojmem starého, ale pečlivě vyrobeného šperku.",
  crafting: "Vyroben z kusu surového malachitu — tvrdého zeleného minerálu s typickými vrstvami v odstínech zelené. Kámen je ručně obroušen do tvaru hrotu a zasazen do stříbrné objímky. Magická vlastnost je do kamene vtištěna při opracování zasvěceným řemeslníkem.",
  history: "",
  trivia: "Malachit je ve světě Aekildae považován za kámen pohybu a rovnováhy. Horníci v movárských dolech věří, že nošení malachitu chrání před pády.",
  image: "img/amulet_pohyblivosti.png",
  blueprint: "img/amulet_pohyblivosti2.png",
  attunement: "Ano",
  relatedIds: []
},
{
  id: "dymka-moudrych-rozhodnuti",
  name: "Dýmka moudrých rozhodnutí",
  categories: ["Magické předměty", "Běžné předměty"],
  subcategory: "Ostatní magické",
  rarity: "Neobvyklý",
  icon: "🪈",
  excerpt: "Ministerstvo zdravotnictví varuje: Kouření škodí zdraví! Zabafej si Hůrecké listí a učiň to nejlepší rozhodnutí svého života.",
  type: "Zázračný předmět (pomůcka)",
  damage: "",
  ac: "",
  cost: "",
  weight: "0.15 kg",
  material: "Tmavé tvrdé dřevo, leštěný povrch",
  properties: "Vyžaduje nabití Hůreckým listím (tabákem).",
  special: "Utracením 1 bodu výdrže (trvale) učiníš nejlepší možné rozhodnutí v dané situaci, nebo si vzpomeneš na zapomenutou informaci. Efekt se aktivuje zabafáním z dýmky naplněné Hůreckým listím.",
  description: "Dýmka moudrých rozhodnutí je klasická dřevěná dýmka vyrobená z tmavého tvrdého dřeva s bohatou hnědou patinou. Má mohutný válcový koš s širokým kruhovým podstavcem a dlouhé elegantně se zužující troubele. Povrch je hladce vyleštěný a nese stopy dlouhého užívání. Vypadá jako běžná námořnická nebo kupecká dýmka — její magická podstata není na první pohled patrná.",
  crafting: "K aktivaci magického efektu je nutné dýmku naplnit speciálním Hůreckým listím — sušenými tabákovými listy pěstovanými v horských oblastech. Listy se nejprve suší, poté ručně krájejí na jemné proužky. Čerstvé listy mají nazelenalou barvu, po usušení a nakrájení získávají tmavě hnědý odstín s výrazným zemitým aroma.",
  history: "",
  trivia: "Nemůžeš zvolit správnou cestu? Nevzpomínáš si, kam jsi založil mapu? Nedokážeš se rychle rozhodnout? Zabafej si Hůrecké listí. Pozor — každé použití trvale odčerpá 1 bod výdrže. Moudrá rozhodnutí mají svou cenu.",
  image: "img/Dymka.png",
  blueprint: "img/Dymka_tabak.png",
  attunement: "Ano",
  relatedIds: []
}
];

const ITEM_CATEGORIES = {
  "Zbraně": { icon: "⚔️", subcats: ["Meče","Obouruční meče","Dýky","Sekery","Obouruční sekery","Palice","Kladiva","Kopí","Hole","Biče","Ostatní zbraně"] },
  "Střelné zbraně": { icon: "🏹", subcats: ["Luky","Kuše","Praky","Pistole","Ostatní střelné"] },
  "Zbroje": { icon: "🛡️", subcats: ["Lehké zbroje","Střední zbroje","Těžké zbroje","Přilby","Rukavice","Boty","Chrániče","Ostatní zbroje"] },
  "Štíty": { icon: "🔰", subcats: ["Malé štíty","Velké štíty","Pavézy","Ostatní štíty"] },
  "Lektvary": { icon: "🧪", subcats: ["Léčivé","Posilující","Ochranné","Jedovaté","Ostatní lektvary"] },
  "Svitky": { icon: "📜", subcats: ["Útočné","Obranné","Užitkové","Ostatní svitky"] },
  "Magické předměty": { icon: "✨", subcats: ["Prsteny","Amulety","Hole a hůlky","Knihy","Ostatní magické"] },
  "Běžné předměty": { icon: "🔧", subcats: ["Nástroje","Jídlo a pití","Oblečení","Světelné zdroje","Lana a řetězy","Ostatní běžné"] },
  "Materiály": { icon: "🪨", subcats: ["Kovy","Dřevo","Kůže","Textil","Kámen","Ostatní materiály"] },
  "Suroviny": { icon: "🌿", subcats: ["Bylinky","Živočišné","Minerální","Magické složky","Ostatní suroviny"] },
  "Munice": { icon: "🎯", subcats: ["Šípy","Šipky (kuše)","Kulky","Vrhací zbraně","Ostatní munice"] },
  "Dopravní prostředky": { icon: "🚢", subcats: ["Lodě","Vozy","Koně a jízdní zvířata","Ostatní doprava"] },
  "Batohy": { icon: "🎒", subcats: ["Batohy","Měšce","Brašny","Vaky","Magické úložné","Ostatní batohy"] },
  "Opasky": { icon: "🪢", subcats: ["Bojové opasky","Užitkové opasky","Magické opasky"] },
  "Pláště": { icon: "🧥", subcats: ["Ochranné pláště","Magické pláště","Běžné pláště"] },
  "Šperky": { icon: "💍", subcats: ["Prsteny (šperk)","Náhrdelníky","Náramky","Čelenky","Brože","Ostatní šperky"] },
  "Ostatní předměty": { icon: "📦", subcats: ["Různé"] }
};
