/* ══════════════════════════════════════════════════════════
   PŘEDMĚTY — Svět Aekildae
   Samostatný datový soubor pro import do wiki
   ══════════════════════════════════════════════════════════ */

ITEMS_DATA = [
{
  id: "einstein-rosenuv-mesec",
  name: "Einstein-Rosenův měšec",
  categories: ["Batohy", "Magické předměty"],
  subcategory: "Měšce",
  rarity: "Vzácný",
  icon: "👝",
  excerpt: "Měšec otevírající cestu do rozdílného časoprostoru. Pojme mnohem víc předmětů, než odpovídá jeho rozměrům.",
  type: "Zázračný předmět (úložný)",
  damage: "",
  ac: "",
  cost: "",
  weight: "0.2 kg",
  material: "Aethericky napuštěná useň, zlatý filigránový vzor",
  properties: "Kapacita: 1000 mincí nebo 250 drahých kamenů. Rozměry: 5 × 10 palců (12,7 × 25,4 cm).",
  special: "Otevírá cestu do rozdílného časoprostoru — vnitřní prostor je mnohonásobně větší než vnější rozměry. Fialová interdimenzionální výplň uvnitř.",
  description: "Einstein-Rosenův měšec je jedním z nejpozoruhodnějších úložných artefaktů, jaké kdy spatřily světlo světa Aekildae. Zvenku se jeví jako elegantní, byť nepříliš nápadný kožený měšec o rozměrech pouhých pěti na deset palců, zdobený jemným zlatým filigránovým vzorem, který se vine po celém povrchu hnědé usně jako kořeny prastarého stromu. Při bližším pohledu si pozorovatel všimne, že ornamenty jemně pulzují v rytmu, který připomíná pomalý tlukot srdce. Uvnitř se otevírá prostor, který nemá žádnou fyzickou analogii v běžném světě — fialově zářící prázdnota, do které lze vložit až tisíc mincí nebo dvě stě padesát drahých kamenů, aniž by měšec zvětšil svůj objem nebo přibral na váze. Tento jev — průchod do jiného časoprostoru — dal měšci jeho jméno.",
  crafting: "Výroba Einstein-Rosenova měšce je mistrovským dílem interdimenzionální alchymie. Základem je useň vyčiněná v éteru — astrální substanci, kterou lze získat pouze za úplňku na místech, kde se protínají ley linie. Useň se napouští aetherickou esencí po dobu třinácti nocí, čímž získá schopnost propouštět hmotu mezi dimenzemi. Zlatý filigrán není pouhá ozdoba — jedná se o stabilizační obvod, který brání kolapsu interdimenzionální kapsy. Verze Mk. II obsahuje navíc vnitřní kapsu pro runový stabilizátor, který prodlužuje životnost měšce. Kruhové dno o průměru 12,7 cm drží celou strukturu pohromadě, zatímco fialová interdimenzionální výplň — vložka o průměru 20 cm — vytváří samotný průchod. Celkový rozvinutý rozměr pláště měšce činí 40,6 × 25,4 cm.",
  history: "O původu tohoto konkrétního měšce se vedou spory. Někteří tvrdí, že pochází z dílen elfských řemeslníků z Ergwienynu, jiní ho přisuzují záhadnému řádu alchymistů, kteří kdysi operovali v Pětiměstí. Jisté je, že technické plánky označené jako Mk. II naznačují existenci starší, méně dokonalé verze.",
  trivia: "Název odkazuje na Einstein-Rosenův most — teoretický průchod časoprostorem. Ve světě Aekildae se tomuto jevu říká 'kapsa v éteru'. Zkušení obchodníci varují před vkládáním živých tvorů do měšce — fialová prázdnota uvnitř neposkytuje vzduch k dýchání.",
  image: "img/casoprostorovy_mesec.png",
  blueprint: "img/einstein-rosenuv-mesec-planek.png",
  attunement: "Ne",
  relatedIds: []
},
{
  id: "maskovaci-plast-amgilched",
  name: "Maskovací Plášť Amgilched",
  categories: ["Pláště", "Magické předměty"],
  subcategory: "Magické pláště",
  rarity: "Velmi vzácný",
  icon: "🧥",
  excerpt: "Plášť kapitána Gefrraye Bricota z Halle. Poskytuje mimořádné maskovací schopnosti a ochranu proti nižší magii.",
  type: "Zázračný předmět (plášť)",
  damage: "",
  ac: "",
  cost: "",
  weight: "2.5 kg",
  material: "Dračí šupiny, zelené listové peří, zlatá spona",
  properties: "+3 na Nenápadnost (s výhodou k hodům). První útok ze zálohy je vždy Kritický.",
  special: "+3 na Nenápadnost — ke všem hodům na Nenápadnost máš výhodu. Tvůj první útok ze zálohy je vždy Kritický zásah. Poskytuje odolnost proti veškerým magickým zásahům kouzly do 4. stupně.",
  description: "Maskovací Plášť Amgilched je výjimečné dílo řemesla, které balancuje na hranici mezi zbrojířstvím, krejčovinou a magickým uměním. Na první pohled upoutá svou neobvyklou strukturou — vnější strana je pokryta vrstvami zelených šupinovitých útvarů, které z dálky připomínají listí prastarého stromu, ale na dotek prozrazují tvrdost dračích šupin. Pravá polovina pláště je pokryta hustým zeleným peřím, jehož jednotlivá pírka mají tvar protáhlých listů, zatímco levá strana přechází v tmavší, kůrovitou texturu připomínající kůru starého dubu. Plášť sepíná na hrudi ozdobná zlatá spona ve tvaru propletených listových úponků — tento motiv se opakuje i v jemném zlatém lemování kapuce a ramen. Vnitřek je z hladké černé látky, která tlumí zvuky pohybu. Spodní okraj je nepravidelně roztřepený jako rozervané listí, což pláště dodává divoký, téměř živý vzhled. Při pohybu plášť jemně šumí jako koruny stromů ve větru.",
  crafting: "Technický plánek Amgilchedu ukazuje čtyři pohledy — přední s rozprostřenými křídly pláště, zadní s detailem šupinové struktury, boční siluetu a detail kapuce. Spona je vyrobena z pozlaceného mithrilu a její listový motiv není pouze dekorativní — slouží jako fokusační bod pro maskovací kouzlo vetřené do tkaniny. Šupiny na povrchu pocházejí z lesního draka a byly jednotlivě přišity elfským hedvábným vláknem, které je na běžném světle neviditelné.",
  history: "Plášť patřil kapitánovi Gefrraye Bricotovi z Halle — muži, jehož jméno se v análech vojenské historie objevuje jen v poznámkách pod čarou, což samo o sobě svědčí o účinnosti jeho pláště. Bricot byl údajně průzkumníkem, který operoval hluboko za nepřátelskými liniemi během Pohraničních válek. Jak plášť získal a kdo jej vyrobil, zůstává tajemstvím — Bricot sám tvrdil, že mu jej daroval les.",
  trivia: "Na dotek plášť působí teplý a suchý bez ohledu na počasí. V dešti voda po šupinách stéká, aniž by promočila vnitřní vrstvu. V úplné tmě zelené šupiny jemně fosforeskují — paradoxně tak plášť v naprosté tmě mírně svítí, ačkoli za denního světla činí nositele téměř neviditelným.",
  image: "img/Amgilched.png",
  blueprint: "img/Amgilched_planek.png",
  attunement: "Ano",
  relatedIds: []
},
{
  id: "amulet-pohyblivosti",
  name: "Amulet pohyblivosti",
  categories: ["Šperky", "Magické předměty"],
  subcategory: "Náhrdelníky",
  rarity: "Neobvyklý",
  icon: "💎",
  excerpt: "Jednoduchý malachitový amulet zlepšující obratnost vlastníka. Stačí jej nosit na krku.",
  type: "Zázračný předmět (amulet)",
  damage: "",
  ac: "",
  cost: "",
  weight: "0.1 kg",
  material: "Malachit, stříbrný splétaný řetízek",
  properties: "Pasivní efekt: Obratnost +1",
  special: "Zvyšuje hodnotu Obratnosti nositele o 1 bod, pokud je nošen na krku. Efekt je pasivní a nevyžaduje aktivaci.",
  description: "Amulet pohyblivosti je nenápadný šperk, který na první pohled nevypadá jako magický předmět — a právě v tom spočívá jeho krása. Na jednoduchém stříbrném splétaném řetízku visí hrubě opracovaný malachitový hrot ve tvaru šípové hlavice. Kámen má sytě zelenou barvu s průsvitnými krystalickými plochami, které na světle lámou paprsky do jemných smaragdových odlesků. Stříbrná objímka drží kámen pevně, ale nenápadně — celý šperk působí dojmem starožitného, ručně vyrobeného amuletu, jaký by mohl nosit lovec nebo průzkumník. Jakmile si jej nositel zavěsí na krk, pocítí jemné brnění v končetinách a jeho pohyby se stanou o poznání plynulejšími.",
  crafting: "Výroba amuletu pohyblivosti začíná výběrem správného kusu surového malachitu. Tento tvrdý zelený minerál s typickými koncentrickými vrstvami v odstínech od světle zelené po téměř černou se těží v movárských kopcích, kde vytváří žíly v měděných ložiscích. Řemeslník musí vybrat kus s nepřerušeným vzorem vrstev — přerušená linie znamená přerušený tok magické energie. Kámen se brousí ručně pomocí diamantových pilníků do tvaru šípového hrotu, přičemž orientace hrotu musí sledovat směr přirozených vrstev v kameni. Magická vlastnost se do malachitu vtiskne při finálním leštění — řemeslník opakuje starou formuli a s každým tahem pilníku vtlačuje do krystalu esenci pohybu. Celý proces trvá tři dny a tři noci bez přerušení.",
  history: "Malachitové amulety mají ve světě Aekildae dlouhou tradici. Staří druidové z Angelwoodu věřili, že malachit je zkamenělý dech větru a nese v sobě jeho rychlost. Lovci z movárského pohraničí nosili hrubé malachitové přívěsky jako talismany pro rychlý úhyb před dravci z pohoří Cruinnece. Až elfští řemeslníci z Ergwienynu přišli na způsob, jak z pověry učinit skutečnou magii — a začali malachitové amulety vyrábět systematicky.",
  trivia: "Horníci v movárských dolech věří, že nošení malachitu chrání před pády a zlepšuje rovnováhu na úzkých chodbách. Malachit přitahuje měď — pokud amulet položíte na stůl vedle měděných mincí, mince se k němu pomalu přibližují. Tento jev nemá žádný praktický význam, ale v hospodách slouží jako oblíbený trik k pobavení.",
  image: "img/amulet_pohyblivosti.png",
  blueprint: "img/amulet_pohyblivosti2.png",
  attunement: "Ano",
  relatedIds: []
},
{
  id: "dymka-moudrych-rozhodnuti",
  name: "Dýmka moudrých rozhodnutí",
  categories: ["Magické předměty", "Běžné předměty"],
  subcategory: "Ostatní magické",
  rarity: "Neobvyklý",
  icon: "🪈",
  excerpt: "Ministerstvo zdravotnictví varuje: Kouření škodí zdraví! Zabafej si Hůrecké listí a učiň to nejlepší rozhodnutí svého života.",
  type: "Zázračný předmět (pomůcka)",
  damage: "",
  ac: "",
  cost: "",
  weight: "0.15 kg",
  material: "Tvrdé ořechové dřevo, vnitřní komora z vypálené hlíny",
  properties: "Vyžaduje nabití Hůreckým listím (tabákem).",
  special: "Utracením 1 bodu výdrže (trvale) učiníš nejlepší možné rozhodnutí v dané situaci, nebo si vzpomeneš na zapomenutou informaci. Efekt se aktivuje zabafáním z dýmky naplněné Hůreckým listím.",
  description: "Dýmka moudrých rozhodnutí vypadá na první pohled jako naprosto obyčejná dřevěná dýmka, jakou uvidíte v rukou každého druhého námořníka, kupce nebo stařešiny v hospodě. Má mohutný válcový koš zasazený do širokého kruhového podstavce a dlouhé, elegantně se zužující troubele z tmavého ořechového dřeva, vyleštěného nesčetnými dotyky do hladké kaštanové patiny. Vnitřek koše je vyložen vypálenou hlínou, která odolává žáru a po letech užívání získala tmavě černý nádech. Žádné runové nápisy, žádné svítící krystaly, žádné stříbrné inkrustace — dýmka svou magickou podstatu prozradí teprve tehdy, když ji naplníte tím správným tabákem a hluboce potáhnete.",
  crafting: "Samotná dýmka je běžný řemeslný výrobek — magii dodává teprve Hůrecké listí. Tento zvláštní tabák se pěstuje výhradně na svazích hory Hůrky v severní Movarii, kde sopečná půda a stálé mlhy vytvářejí jedinečné podmínky. Listy se sklízejí před úsvitem, kdy jsou ještě pokryty ranní rosou nasáklou éterickou energií z horských pramenů. Čerstvé listy mají nazelenalou barvu a voní po mokré trávě. Sušení trvá přesně dvacet jedna dní na dřevěných roštech z jasanového dřeva — jasan zesiluje věštecké vlastnosti listí. Po usušení se listy ručně krájejí na jemné proužky, které získávají tmavě hnědý odstín s výrazným zemitým aroma připomínajícím směs mechu, vlhkého dřeva a vzdálené bouřky.",
  history: "Podle lidové tradice první Dýmku moudrých rozhodnutí vyřezal bezejmenný pastýř, který se ztratil v horách a tři dny bloudil v mlze. Když z posledních sil zapálil dýmku naplněnou místním plevelným listím, náhle s naprostou jistotou věděl, kudy jít. Sestoupil z hor za dva dny a do konce života si nechal zasílat pytle onoho plevele. Pravda je zřejmě prozaičtější — účinky Hůreckého listí pravděpodobně objevili druidové z Angelwoodu, kteří experimentovali s horskými rostlinami.",
  trivia: "Nemůžeš zvolit správnou cestu? Nevzpomínáš si, kam jsi založil mapu? Nedokážeš se rychle rozhodnout? Zabafej si Hůrecké listí! Pozor však — každé použití trvale odčerpá 1 bod výdrže. Moudrá rozhodnutí mají svou cenu a žádný mudrc jich neučinil nekonečné množství. Zkušení uživatelé doporučují šetřit dýmku na skutečně zásadní momenty — na volbu cesty na křižovatce v temném hvozdu stačí zdravý rozum.",
  image: "img/Dymka.png",
  blueprint: "img/Dymka_tabak.png",
  attunement: "Ano",
  relatedIds: []
}
];

ITEM_CATEGORIES = {
  "Zbraně": { icon: "⚔️", subcats: ["Meče","Obouruční meče","Dýky","Sekery","Obouruční sekery","Palice","Kladiva","Kopí","Hole","Biče","Ostatní zbraně"] },
  "Střelné zbraně": { icon: "🏹", subcats: ["Luky","Kuše","Praky","Pistole","Ostatní střelné"] },
  "Zbroje": { icon: "🛡️", subcats: ["Lehké zbroje","Střední zbroje","Těžké zbroje","Přilby","Rukavice","Boty","Chrániče","Ostatní zbroje"] },
  "Štíty": { icon: "🔰", subcats: ["Malé štíty","Velké štíty","Pavézy","Ostatní štíty"] },
  "Lektvary": { icon: "🧪", subcats: ["Léčivé","Posilující","Ochranné","Jedovaté","Ostatní lektvary"] },
  "Svitky": { icon: "📜", subcats: ["Útočné","Obranné","Užitkové","Ostatní svitky"] },
  "Magické předměty": { icon: "✨", subcats: ["Prsteny","Amulety","Hole a hůlky","Knihy","Ostatní magické"] },
  "Běžné předměty": { icon: "🔧", subcats: ["Nástroje","Jídlo a pití","Oblečení","Světelné zdroje","Lana a řetězy","Ostatní běžné"] },
  "Materiály": { icon: "🪨", subcats: ["Kovy","Dřevo","Kůže","Textil","Kámen","Ostatní materiály"] },
  "Suroviny": { icon: "🌿", subcats: ["Bylinky","Živočišné","Minerální","Magické složky","Ostatní suroviny"] },
  "Munice": { icon: "🎯", subcats: ["Šípy","Šipky (kuše)","Kulky","Vrhací zbraně","Ostatní munice"] },
  "Dopravní prostředky": { icon: "🚢", subcats: ["Lodě","Vozy","Koně a jízdní zvířata","Ostatní doprava"] },
  "Batohy": { icon: "🎒", subcats: ["Batohy","Měšce","Brašny","Vaky","Magické úložné","Ostatní batohy"] },
  "Opasky": { icon: "🪢", subcats: ["Bojové opasky","Užitkové opasky","Magické opasky"] },
  "Pláště": { icon: "🧥", subcats: ["Ochranné pláště","Magické pláště","Běžné pláště"] },
  "Šperky": { icon: "💍", subcats: ["Prsteny (šperk)","Náhrdelníky","Náramky","Čelenky","Brože","Ostatní šperky"] },
  "Ostatní předměty": { icon: "📦", subcats: ["Různé"] }
};
